### ISSUE TITLE
Modify the token endpoint response body before sending

### ISSUE THREAD

**Issue by thizzle** [domenic/restify-oauth2#25]
I need to modify the response for the token endpoint. Is there any way to insert some middleware that runs *after* the token grant middleware?

Restify does not allow stacking middlewares for a specific route using multiple sequential calls to `server.VERB`. If that was the case, I could stack another middleware function onto the token grant route by adding a route handler *after* calling the restify-oauth2 hook:

    require('restify-oauth2').ropc(options)
    server.post("/token", function(req, res, next) {})

So is there a recommended way to accomplish this?

**Comment by gmaniac** [comment]
I would recommend creating a separate route and generating a token via the `hooks.js` file using `grantUserToken` then you can alter the response however you like

 Let me know if you need some examples for this.
