### ISSUE TITLE
Restify 3

### ISSUE THREAD

**Issue by ramiel** [domenic/restify-oauth2#30]
Can you test if this works with restify 3.x and update peerDependencies?

**Comment by LOLKFC** [comment]
+1

**Comment by airroom** [comment]
:+1:

**Comment by markotom** [comment]
+1

**Comment by gmaniac** [comment]
Sorry for the delay, doing this today. I will let you know when I have everything updated.

**Comment by gmaniac** [comment]
commit f26c5602d0033d56caff7bdc794886128ce1a933
