### ISSUE TITLE
 The package restify does not satisfy its siblings' peerDependencies requirements

### ISSUE THREAD

**Issue by mike-aungsan** [domenic/restify-oauth2#32]
npm ERR! peerinvalid The package restify does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer restify-oauth2@4.0.2 wants restify@2.x

**Comment by gmaniac** [comment]
I am going to be updating dependencies today, that should fix this.

**Comment by gmaniac** [comment]
I updated `peerDependencies` it now uses `restify 3.x`

commit f26c5602d0033d56caff7bdc794886128ce1a933

**Comment by mike-aungsan** [comment]
Does it work with 4.x?

**Comment by gmaniac** [comment]
Thank you for pointing this out. I don't know what I was thinking when I responded to this. I will update this and push up. I have updated them, but test are not passing.

**Comment by mike-aungsan** [comment]
I just install on a new host with restify 4.0 again today. 

Your package.json still has 3.x

"peerDependencies": {
    "restify": "3.x"
},

**Comment by pedromarce** [comment]
This is still not working, everything seems to be working fine with peerDepencies changed to restify 4.x, is there any problem doing so?
