### ISSUE TITLE
Restify 4.x support

### ISSUE THREAD

**Issue by NormandoHall** [domenic/restify-oauth2#38]
Please, can you made restify 4.x support?

Regards

**Comment by ckcfcc** [comment]
yes. plz support restify 4

**Comment by gmaniac** [comment]
Sorry for the delay on this been really busy. I am working on this in the next couple of days.

I have added it I am working on getting tests to pass then I will update the package.

**Comment by nmathon** [comment]
:+1: 
Can you push a dev branch so we can test it with you / help you ?

**Comment by gmaniac** [comment]
Pushed, sorry I have not been able to work on this recently. All PRs welcome.

https://github.com/domenic/restify-oauth2/tree/develop

I removed all the things I have been testing, this is just the dependency updates.

**Comment by jocull** [comment]
You can setup npm to use the version with just the updated dependencies short-term:
```
"restify-oauth2": "git://github.com/domenic/restify-oauth2.git#cf5837d6b695c3d98264e53854b3b6d8f1fd4d2f",
```

**Comment by InsidiousForce** [comment]
What's the status here? I see 4.0.3 of restify-oauth2 in npm, on github the latest release is 4.0.0 from april 2014 and the 4.0.3 in npm requires a peer of restify-3.x - is there a different fork that is working with restify 4.x or is this still the defacto? Best to use the commit above pointing to a fictional 4.0.4 for now? Thank you

**Comment by jocull** [comment]
I've been using the commit above until it's sorted. I haven't had any
issues with it, but we're not in production yet either.

**Comment by InsidiousForce** [comment]
Thanks for the info, it's working fine for me as well, also not in production.

**Comment by AlexDobeck** [comment]
Submitted a pull request to resolve tests. Hoping that is enough to get this deployed to npm #40.

**Comment by Z-starts** [comment]
+1 plz support

**Comment by gmaniac** [comment]
#40 Merged and published
