### ISSUE TITLE
Confusion about Implementing with passport-facebook

### ISSUE THREAD

**Issue by netpoetica** [domenic/restify-oauth2#5]
I am trying to grok the placement of this module in my application, because it appears to be the piece I am missing in my Restify/passport/passport-facebook app. With passport-facebook, I have the ability to have the user log in to Facebook, and when the user object is returned I can seek a match in my database and say "Oh hey yes, this user has a profile" or "no, create a profile" - but after that initial callback, I no longer have any authorization methods for my RESTful API. 

Would I use restify-oauth2 in combination with passport and passport-facebook in order to achieve this, or do I just need to write a similar token passing mechanism that passport is completely missing?

Thanks!

**Comment by gmaniac** [comment]
Are you still needing help with this @netpoetica?
